server:
  port: 8080
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: mrcoole
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: exercisetrackingsystem@gmail.com
    password: myPassword
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true 
        starttls.enable: true
        ssl.trust: smtp.gmail.com  

  
  jpa:
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      
      ddl-auto: create-drop
